// "use client";

import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Amenti | Portfolio",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex items-center justify-center h-screen bg-zinc-100 dark:bg-gray-900 px-32">
      {/* Left Section: Image */}
      <div className="w-1/2 flex justify-center items-center">
        <div className="relative w-72 h-96">
          <Image
            src="/assets/images/profile.jpg" // Correct path to your image in the public folder
            alt="Amenti Kebede"
            fill // Replaces layout="fill"
            style={{ objectFit: "cover" }} // Replaces objectFit="cover"
          />
        </div>
      </div>

      {/* Right Section: Content */}
      <div className="w-1/2 p-6 flex flex-col items-start space-y-6">
        {/* Name */}
        <h1 className="text-5xl font-bold text-black dark:text-white">
          AMENTI KEBEDE
        </h1>

        {/* Professions */}
        <h2 className="text-2xl text-lime-500 dark:text-yellow-300">
          Website Developer, UI/UX Designer, Mobile App Developer
        </h2>

        {/* Description */}
        <p className="text-lg text-gray-800 dark:text-gray-300">
          I am a website and mobile application developer based in Addis Ababa,
          and I’m very passionate and dedicated to my work.
        </p>

        {/* Buttons */}
        <div className="flex space-x-4">
          {/* Telegram Button */}
          <Link href="https://t.me/your_telegram" passHref>
            <button className="px-4 py-2 bg-lime-500 text-white rounded-md hover:bg-lime-600 transition">
              Say Hello on Telegram
            </button>
          </Link>

          {/* My Works Button */}
          <Link href="/projects" passHref>
            <button className="px-4 py-2 bg-gray-800 text-white rounded-md hover:bg-gray-700 transition">
              My Works
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
}
